[versions]
guava = "32.1.2-jre"
gradleplugin = "1.1.0"
kotlin = "1.9.10"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava"}
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
gradle-publish = { id = "com.gradle.plugin-publish", version.ref = "gradleplugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
